version: '2'
services:
  mongo:
    image: mongo:3.4
    volumes:
      - /data/db
  flask_mongodb:
    build: .
    ports:
      - "80:5000"
    environment:
      - PORT=5000
      - MONGODB_URL=mongo:27017
      - SECRET_KEY=1234567890asdfghjkl
    links:
      - mongo 
    depends_on: 
      - mongo